#!groovy

pipeline {
    agent any
    
    tools {nodejs "NodeJS"}

    stages {
        stage('Clean Workspace') {
            steps {
                sh 'dir'
                cleanWs()
                sh 'dir'
            }
        }
        
        stage('Configure NodeJS and Git') {
            steps {
                sh 'npm config set registry https://registry.npmjs.org/'
                sh 'npm config set strict-ssl false'
                sh 'git config --global http.sslVerify false'
            }
        }

        stage('Cloning from Git') {
            steps {
                git 'https://github.com/sas92/PrismMockServer'
            }
        }

        // stage('Install Prism NPM Module Globally') {
        //     steps {
        //         sh 'npm install -g @stoplight/prism-cli'
        //     }
        // }

        // stage('Install NPM Dependencies') {
        //     steps {
        //         sh 'npm install'
        //     }
        // }

        stage('Deploy to PCF') {
            steps {
                pushToCloudFoundry(
                    target: 'api.run.pivotal.io',
                    organization: 'Sastech',
                    cloudSpace: 'development',
                    credentialsId: 'sas_pcf_cred',
                    pluginTimeout: '240'
                )
            }
        }
    }
}